# Generated by Django 2.0.4 on 2018-07-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssocMgnt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='realName',
            field=models.CharField(max_length=32, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, '社团创立者'), (1, '教务员工'), (2, '系统管理员')], default=0, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=48, null=True, verbose_name='联系电话'),
        ),
    ]
