# Generated by Django 2.0.4 on 2018-07-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssocMgnt', '0002_auto_20180710_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='association',
            options={'verbose_name': '4.社团', 'verbose_name_plural': '4.社团'},
        ),
        migrations.AlterModelOptions(
            name='bulletinapplication',
            options={'verbose_name': '9.公告发布申请', 'verbose_name_plural': '9.公告发布申请'},
        ),
        migrations.AlterModelOptions(
            name='eventapplication',
            options={'verbose_name': '7.活动申请', 'verbose_name_plural': '7.活动申请'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '3.地点', 'verbose_name_plural': '3.地点'},
        ),
        migrations.AlterModelOptions(
            name='locationapplication',
            options={'verbose_name': '8.场所申请', 'verbose_name_plural': '8.场所申请'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '5.社团成员', 'verbose_name_plural': '5.社团成员'},
        ),
        migrations.AlterModelOptions(
            name='registrationapplication',
            options={'verbose_name': '6.社团注册申请', 'verbose_name_plural': '6.社团注册申请'},
        ),
        migrations.AlterModelOptions(
            name='stuffpermission',
            options={'verbose_name': '2.教务员工权限', 'verbose_name_plural': '2.教务员工权限'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '1.用户', 'verbose_name_plural': '1.用户'},
        ),
        migrations.AddField(
            model_name='bulletinapplication',
            name='noticed',
            field=models.BooleanField(default=False, verbose_name='学生已阅'),
        ),
        migrations.AddField(
            model_name='eventapplication',
            name='noticed',
            field=models.BooleanField(default=False, verbose_name='学生已阅'),
        ),
        migrations.AddField(
            model_name='locationapplication',
            name='noticed',
            field=models.BooleanField(default=False, verbose_name='学生已阅'),
        ),
        migrations.AddField(
            model_name='registrationapplication',
            name='noticed',
            field=models.BooleanField(default=False, verbose_name='学生已阅'),
        ),
    ]
