# Generated by Django 2.0.4 on 2018-07-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssocMgnt', '0003_auto_20180711_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='deletionMark',
            field=models.BooleanField(default=False, verbose_name='解散标记'),
        ),
        migrations.AddField(
            model_name='association',
            name='deletionReason',
            field=models.TextField(null=True, verbose_name='解散原因'),
        ),
        migrations.AddField(
            model_name='association',
            name='deletionTime',
            field=models.DateTimeField(null=True, verbose_name='解散倒计时'),
        ),
    ]
