# Generated by Django 2.0.4 on 2018-07-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssocMgnt', '0005_user_uid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StuffPermission',
            new_name='StaffPermission',
        ),
    ]
